# Generated by Django 3.2.9 on 2023-07-01 12:31

import bookstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_alter_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, default=bookstore.models.generate_isbn, max_length=13, null=True, unique=True),
        ),
    ]
